oauthClient:
  redirectUris:
    - http://localhost:8080/callback
  applicationType: browser
trustedOrigins: 
  - http://localhost:8080

directions: |+2
  Okta configuration written to: .okta.env
  
  Build and Run Vue Single Page App:
      cd spa
      npm install
      npm start

  Build and Run Express Resource Server:
      cd resource-server
      npm install
      npm start